### ISSUE TITLE
handle shipment file: when a shipment file with 2 devices is moved to the import directory, , the file is moved to the 'done' directory instead off the 'failed' directory.

### ISSUE THREAD

**Issue by klvries** [OSGP/Platform#153]
handle shipment file: when a shipment file with **2 devices** is moved to the import directory, , the file is moved to the 'done' directory instead off the 'failed' director

I used two times the same file.

The logging:

```
13:18:13.167 [Thread-17] INFO  (DirectoryWatcher.java:80) c.a.o.s.w.infra.io.DirectoryWatcher - New file was placed in /home/flexadmin/shipment/unencrypted/import
13:18:13.168 [Thread-17] INFO  (UnencryptedShipmentFileDirectoryWatcher.java:39) c.a.o.s.w.i.i.UnencryptedShipmentFileDirectoryWatcher - Processing unencrtypted file: {}unencrypted.xml
13:19:23.383 [pool-10-thread-1] INFO  (ShipmentFileHandler.java:245) c.a.o.s.w.i.io.ShipmentFileHandler - Finished processing /home/flexadmin/shipment/unencrypted/done/unencrypted_20150923-13:18:13.xml
13:19:23.384 [pool-10-thread-1] INFO  (ShipmentFileCleanupThread.java:35) c.a.o.s.w.i.i.ShipmentFileCleanupThread - Delay over for thread of shipmentFile: 22
13:20:02.019 [pool-18-thread-1] INFO  (DeviceMonitoringService.java:162) c.a.o.n.a.s.DeviceMonitoringService - Check for power usage data for all devices in a month from 2015-07-31T00:00:00.000Z untill 2015-08-31T00:00:00.000Z .
```

**Comment by thijlboonen** [comment]
The issue here is that it's not clear yet what has to happen when a shipment file contains a double device_id (equipment_identifier). At the moment, the code checks if a device already exists in the SMA database and if it does, it ignores it and moves on. 

In this case, 2 double devices are in the shipment file and both will be ignored. After the delay, the thread will put the shipment file in done (because it doesn't have a FAILED status) and the results.txt will be empty, because no device was linked to the shipment file

**Comment by smvdheijden** [comment]
When a shipment file contains a double device_id, the shipment file should be rejected

**Comment by klvries** [comment]
Now it works fine .

When the filwe contains an already existing device, the complete file is rejected, and the 'equipment identifier' of the double device is shown in the error.csv
